name: Build Project
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Cache ARM GCC Toolchain
        uses: actions/cache@v3
        with:
          path: /usr/local/arm-toolchain
          key: ${{ runner.os }}-arm-toolchain

      - name: Install ARM GCC Toolchain
        run: |
          sudo mkdir -p /usr/local/arm-toolchain
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build project
        run: |
          make -j$(nproc) V=1
        shell: bash
