name: Build Project
on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive" # Ensure submodules are checked out

      - name: Install ARM GCC Toolchain
        run: |
          brew install arm-none-eabi-gcc

      - name: Build project
        run: |
          make -j $(sysctl -n hw.ncpu) V=1
        shell: bash
